Alex_Razvan
gabimoisa/LigaAC pull request #2
Opened 2024-05-16 06:54 UTC by RazvanGolan

Html &  client-side JavaScript source code scanning on web pages with sandbox: Right click on a web page will have a option to scan with OPSWAT Chrome extension. The scan will be done with sandbox. 
Also added a new column in Scan History Table, where the sandbox verdict can be seen.

2024-05-20 13:15 UTC, roxanabogdanandreea requested changes

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/background/background-task.js
> +            console.log("Click din pagina", info.pageUrl);
please remove console

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/file-processor.js
> +            if(info.additional_info == 'sandbox') {
info?.additional_info so we don't crash the page if info is undefined

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/file-processor.js
> +                const sha1 = info.file_info.sha1;
info?.file_info?.sha1

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/file-processor.js
> +                console.log('sandboxLookup', response);
please remove console

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/file-processor.js
> +                const lowercasedVerdict = response.final_verdict.verdict.charAt(0) + response.final_verdict.verdict.substring(1).toLowerCase();
undefined.substring() or charAt() will throw a SyntaxError. Add ? to make sure it doesn't crash the page

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/file-processor.js
> +                file.sandboxVerdict = "No dynamic analysis was performed";
Please change to `No dynamic analysis performed`

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/file-processor.js
> +        console.log("FILE VERDICT FINAL", file);
please remove console

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/metascan-client.js
> +    console.log('fileUpload metascan-client', sampleSharing, options);
remove console

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/metascan-client.js
>          console.warn(error);
remove console

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/metascan-client.js
> + * https://api.metadefender.com/v4/hash/02637A8DA752611218FCEA1854052B9FF160AFD2/sandbox
remove the hash from the comment 
https://api.metadefender.com/v4/hash/{hash}/sandbox

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/metascan-client.js
> +    // console.log(restEndpoint);
please remove commented console

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/common/metascan-client.js
> +    if (response.error) {
you should  throw new Error here instead of ignoring it and add a try catch in poolForSandboxResults and Reject the promise with the error

2024-05-20 13:15 UTC, roxanabogdanandreea commented on src/services/constants/workflow.js
> +export const SANDBOX_TIMEOUT = 'long';
SANDBOX_TIMEOUT can be removed, we don't need to send it as a header

2024-05-20 13:18 UTC, roxanabogdanandreea commented on src/components/scan-history-table/ScanHistoryTableRow.js
> +    const SandBox = classNames({
please rename to `Sandbox`

2024-05-23 06:46 UTC, gabimoisa commented
![Screenshot from 2024-05-23 09-27-04](https://github.com/gabimoisa/LigaAC/assets/71866282/4b3aa927-6acb-4d4d-ba61-7a013dad8c20)

The page should be responsive. The sandbox verdict column must also be visible on small screens. You must have padding on the right as well as on the left. Also, you have to keep the border on the table and on the smaller screens

2024-05-23 06:55 UTC, gabimoisa commented
Please update all the tests to work. The tests are run with the command "mocli test".

2026-04-30 10:04 UTC, closed without merging